# Node.js

# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  displayName: 'Install Node'
  inputs:
    versionSpec: '12.16.1'
    
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      sed -i "s/localhost/$SERVICEADDRESS/" .env
      cp .env .env.production
  env:
    SERVICEADDRESS: $(ServiceAddress)
  displayName: 'Replace api address value'

- script: |
    npm install
    npm run eject
    npm run link-icons
    # npm run android
  workingDirectory: src
  displayName: 'Install node dependencies'

- task: Bash@3
  inputs:
    filePath: 'scripts/add-permissions.sh'
  displayName: 'Add Photo permissions for android'

- task: Gradle@2
  inputs:
    workingDirectory: 'android'
    gradleWrapperFile: 'android/gradlew'
    gradleOptions: '-Xmx3072m'
    publishJUnitResults: false
    # testResultsFiles: '**/TEST-*.xml'
    tasks: 'assembleRelease'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      find $directory -type f -name "*.apk"


- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/android/app/build/outputs/apk/release'
    Contents: 'app-release.apk'
    TargetFolder: '$(build.artifactstagingdirectory)'


- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'StudyingSquirrelsAPK'
    publishLocation: 'Container'


# - task: AndroidSigning@3
#   inputs:
#     apkFiles: '**/*.apk'
#     apksignerKeystoreFile: '*studyingsquirrels.keystore'
#     apksignerKeystorePassword: 'zJyiOuDNB0G5ZgGJv5jy'
#     zipalign: false
# - task: PublishBuildArtifacts@1
#   inputs:
#     PathtoPublish: '$(Build.SourcesDirectory)/*.apk'
#     ArtifactName: 'StudyingSquirrelsAPK'
#     publishLocation: 'Container'